### ISSUE TITLE
Usage of rfactory in karma runner / jasmine / requirejs 

### ISSUE THREAD

**Issue by mstefaniuk** [achudnovskij/rfactory#2]
I like direction taken with rfactory RequireJS plugin to provide dependency factories. I'm running unit tests with karma. I've prepared a sample configuration but currently I'm receiving an error "Please ensure that rinject plugin is loaded before any modules you try to resolve". Plese check https://gist.github.com/mstefaniuk/2e12de73e6e0ed548a4e

Could you provide guidelines how to use rfactory with it?

**Comment by achudnovskij-zz** [comment]
Hi,
The plugin requires 'rfactory' module to be loaded before any test modules or dependencies you try to mock.

In test.main.js configuration:
`- deps: ['rfactory'].concat(tests),`
doesn't guarantee you any order. So a test or it's dependency can be loaded before the plugin.

It can be resolved by ensuring the explicit order of files loading.
For example, in test.main.js:

```
var tests = []; 
// your existing logic to collect files
requirejs.config({
    baseUrl: '/base/app',
    paths: {
        rfactory: '../lib/rfactory'
    },
    deps:['rfactory'] // this is loaded before any requirejs module
});
require(tests, function(){
    window.__karma__.start();
}   
```

Or 

```
var tests = []; 
// your existing logic to collect files
requirejs.config({
    baseUrl: '/base/app',
    paths: {
        rfactory: '../lib/rfactory'
    }
});
require(['rfactory'], function(){
   require(tests, function(){
      window.__karma__.start();
   }   
})
```

**Comment by achudnovskij-zz** [comment]
One more suggestion: 
For a new project I would recommend replacing 'Jasmine' with 'Mocha' + 'chaijs' + 'sinon'
I choose Jasmine for the example since it's one single library so it's makes the example more compact.

For the real code:
- The combination above offers more features then 'Jasmine' solely. 
- 'Mocha' doesn't require workarounds to load tests with requirejs. Workarounds are in https://github.com/achudnovskij/rfactory/blob/master/example/spec/SpecRunner.html I'm not 100% they will work fine with Karma/PhantomJs

I have a small example of Karma + Mocha setup: https://github.com/achudnovskij/mocha-incremental-boilerplate . I's set up to run through Grunt but it has karma configuration

**Comment by mstefaniuk** [comment]
It looks that in my case it was stupid error in `under-test.js`:

``` javascript
define(['dependency', function(dependency){
    return {
        check: function() {
            dependency.callMe('kuku');
        }
    };
}]);
```

within define call there was unclosed dependency list square bracket (Angular alike). After fixing it behaves as expected even with `deps: ['rfactory'].concat(tests)`.

**Comment by achudnovskij-zz** [comment]
Ok, 
Anyway, I think your test run logic can benefit from the fix I propose. There is a risk of failing unexpectedly because of script loading sequence. It can potentially make the test runner unstable.
Thanks!

**Comment by mstefaniuk** [comment]
I would explore your approach once more. In example specs of `rfactory` (in `rfactory/blob/master/example/spec/SpecRunner.html`) there is:

```
require(['domready!', 'rfactory','spec/unit/indexView', 'spec/functional/indexView'], function(){
  window.onLoadHandler();
});
```

and I think that it is the same as `deps: ['rfactory'].concat(tests)`.

Do you expect any differences?

**Comment by achudnovskij-zz** [comment]
Hi,

No differences, I'll push a change with a comment today.
This should be split into 2 require calls to enforce the sequence.
It's likely to cause instability with real examples.

Please let me know is you face any issues with setting this up with karma.
I can help.
We use this injection technique and run 2k+ tests in karma and in browser.

Thanks!
Andrey
